language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
services:
  - postgresql
env:
  global:
    - PGPORT=5432
before_script:
  - npm install
  - npm run build
  - psql -c 'create database questionerdb;' -U postgres
  - npm run travis-db.js
script:
  - npm test
after_success:
  - npm run coverage